{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8bee33dc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "⬇️  Descargando model.pkl desde GitHub...\n",
      "✅ model.pkl descargado correctamente.\n",
      "⬇️  Descargando features.pkl desde GitHub...\n",
      "✅ features.pkl descargado correctamente.\n",
      "⬇️  Descargando target_encodings.pkl desde GitHub...\n",
      "✅ target_encodings.pkl descargado correctamente.\n",
      "🚀 Modelo y artefactos cargados. API lista para recibir peticiones.\n",
      "\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: on\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on all addresses (0.0.0.0)\n",
      " * Running on http://127.0.0.1:5000\n",
      " * Running on http://192.168.0.13:5000\n",
      "Press CTRL+C to quit\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, request\n",
    "from flask_restx import Api, Resource, fields\n",
    "import joblib\n",
    "import numpy as np\n",
    "import requests\n",
    "import os\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 1. Configuración: URLs de los artefactos en GitHub\n",
    "# ------------------------------------------------------------\n",
    "GITHUB_RAW_BASE = \"https://raw.githubusercontent.com/CrisSCon/MIAD_ML_NLP_2026_Disponibilizacion1/main\"\n",
    "\n",
    "MODEL_URL = f\"{GITHUB_RAW_BASE}/model.pkl\"\n",
    "FEATURES_URL = f\"{GITHUB_RAW_BASE}/features.pkl\"\n",
    "ENCODINGS_URL = f\"{GITHUB_RAW_BASE}/target_encodings.pkl\"\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 2. Función para descargar archivos si no existen localmente\n",
    "# ------------------------------------------------------------\n",
    "def download_file(url, local_path):\n",
    "    \"\"\"Descarga un archivo desde una URL si no existe localmente.\"\"\"\n",
    "    if not os.path.exists(local_path):\n",
    "        print(f\"⬇️  Descargando {local_path} desde GitHub...\")\n",
    "        r = requests.get(url)\n",
    "        r.raise_for_status()\n",
    "        with open(local_path, \"wb\") as f:\n",
    "            f.write(r.content)\n",
    "        print(f\"✅ {local_path} descargado correctamente.\")\n",
    "    else:\n",
    "        print(f\"📁 Usando archivo local: {local_path}\")\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 3. Descargar y cargar los artefactos\n",
    "# ------------------------------------------------------------\n",
    "download_file(MODEL_URL, \"model.pkl\")\n",
    "download_file(FEATURES_URL, \"features.pkl\")\n",
    "download_file(ENCODINGS_URL, \"target_encodings.pkl\")\n",
    "\n",
    "model = joblib.load(\"model.pkl\")\n",
    "FEATURE_NAMES = joblib.load(\"features.pkl\")\n",
    "target_encodings = joblib.load(\"target_encodings.pkl\")\n",
    "global_mean = target_encodings[\"global_mean\"]\n",
    "\n",
    "print(\"🚀 Modelo y artefactos cargados. API lista para recibir peticiones.\\n\")\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 4. Funciones de feature engineering (idénticas al entrenamiento)\n",
    "# ------------------------------------------------------------\n",
    "def create_raw_features(row):\n",
    "    \"\"\"Crea las variables derivadas: log, interacciones, etc.\"\"\"\n",
    "    d = row.copy()\n",
    "    d['durlog'] = np.log1p(d['duration_ms'])\n",
    "    d['eneloud'] = d['energy'] * d['loudness']\n",
    "    d['danval'] = d['danceability'] * d['valence']\n",
    "    d['isinstr'] = int(d['instrumentalness'] > 0.45)\n",
    "    d['expl'] = int(d['explicit'])\n",
    "    return d\n",
    "\n",
    "def add_target_encodings(row):\n",
    "    \"\"\"Agrega las columnas de target encoding con suavizado global.\"\"\"\n",
    "    artist = row.get('artists', '')\n",
    "    genre = row.get('track_genre', '')\n",
    "    album = row.get('album_name', '')\n",
    "    row['artistste'] = target_encodings['artists'].get(artist, global_mean)\n",
    "    row['track_genrete'] = target_encodings['track_genre'].get(genre, global_mean)\n",
    "    row['album_namete'] = target_encodings['album_name'].get(album, global_mean)\n",
    "    return row\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 5. Configuración de Flask‑RESTX\n",
    "# ------------------------------------------------------------\n",
    "app = Flask(__name__)\n",
    "api = Api(\n",
    "    app,\n",
    "    version='1.0',\n",
    "    title='Spotify Popularity API',\n",
    "    description='Predicción de popularidad de canciones (Stacking XGB + LGBM)'\n",
    ")\n",
    "\n",
    "ns = api.namespace('predict', description='Predicción de popularidad')\n",
    "\n",
    "# Parser (usando ns.parser() para que Swagger lo documente)\n",
    "parser = ns.parser()\n",
    "numeric_params = [\n",
    "    'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',\n",
    "    'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',\n",
    "    'valence', 'tempo'\n",
    "]\n",
    "for param in numeric_params:\n",
    "    parser.add_argument(param, type=float, required=True, location='args')\n",
    "\n",
    "parser.add_argument('artists', type=str, required=True, location='args')\n",
    "parser.add_argument('track_genre', type=str, required=True, location='args')\n",
    "parser.add_argument('album_name', type=str, required=True, location='args')\n",
    "\n",
    "# Modelo de respuesta para Swagger\n",
    "resource_fields = api.model('Resource', {\n",
    "    'popularity': fields.Float,\n",
    "})\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 6. Endpoint\n",
    "# ------------------------------------------------------------\n",
    "@ns.route('/')\n",
    "class PredictPopularity(Resource):\n",
    "\n",
    "    @ns.doc(parser=parser)\n",
    "    @ns.marshal_with(resource_fields)\n",
    "    def get(self):\n",
    "        \"\"\"Predicción vía GET con parámetros en la URL\"\"\"\n",
    "        args = parser.parse_args()\n",
    "        return self._predict(args)\n",
    "\n",
    "    def post(self):\n",
    "        \"\"\"Predicción vía POST con JSON en el cuerpo\"\"\"\n",
    "        data = request.get_json()\n",
    "        return self._predict(data)\n",
    "\n",
    "    def _predict(self, args):\n",
    "        # Convertir argumentos a diccionario\n",
    "        row = {k: v for k, v in args.items()}\n",
    "        # Aplicar feature engineering\n",
    "        row = create_raw_features(row)\n",
    "        row = add_target_encodings(row)\n",
    "        # Construir array en el orden exacto que espera el modelo\n",
    "        X = np.array([row[name] for name in FEATURE_NAMES]).reshape(1, -1)\n",
    "        # Predecir y limitar al rango [0, 100]\n",
    "        pred = model.predict(X)[0]\n",
    "        pred = float(np.clip(pred, 0, 100))\n",
    "        return {\"popularity\": pred}, 200\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 7. Lanzar la aplicación\n",
    "# ------------------------------------------------------------\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True, use_reloader=False, host='0.0.0.0', port=5000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ffd5839",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
